"use client";

import Image from "next/image";
import { FormEvent, useEffect, useState } from "react";

type Severity = "Critical" | "High" | "Medium" | "Low" | "Info";

type Issue = {
  title: string;
  severity: Severity | string;
  plainEnglishExplanation: string;
  technicalDetail: string;
  historicalMatch: string | null;
  historicalMatchSummary: string | null;
};

type Report = {
  overallRiskScore: number;
  summary: string;
  issues: Issue[];
};

type ScanSuccess = {
  address: string;
  contractName: string | null;
  truncated: boolean;
  report: Report;
};

const EXAMPLE_CONTRACTS = [
  {
    label: "Try USDC",
    address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
  },
  {
    label: "Try Uniswap Router",
    address: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D",
  },
  {
    label: "Try WETH",
    address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
  },
] as const;

const LOADING_MESSAGES = [
  "Fetching contract source...",
  "Analyzing with AI...",
] as const;

const NAV_LINKS = [
  { label: "Home", href: "#top" },
  { label: "Scan", href: "#scan" },
  { label: "About", href: "#about" },
  { label: "Report", href: "#report" },
] as const;

function riskTone(score: number): { chip: string; label: string } {
  if (score <= 3) {
    return {
      chip: "border-emerald-300/30 bg-emerald-400/15 text-emerald-300",
      label: "Low risk",
    };
  }
  if (score <= 6) {
    return {
      chip: "border-amber-300/30 bg-amber-400/15 text-amber-200",
      label: "Moderate risk",
    };
  }
  return {
    chip: "border-rose-300/30 bg-rose-400/15 text-rose-300",
    label: "High risk",
  };
}

function severityTone(severity: string): string {
  switch (severity) {
    case "Critical":
      return "border-rose-400/30 bg-rose-500/20 text-rose-200";
    case "High":
      return "border-orange-400/30 bg-orange-500/20 text-orange-200";
    case "Medium":
      return "border-amber-400/30 bg-amber-500/20 text-amber-100";
    case "Low":
      return "border-cyan-400/30 bg-cyan-500/20 text-cyan-200";
    default:
      return "border-white/15 bg-white/10 text-violet-100";
  }
}

function formatReportAsText(data: ScanSuccess): string {
  const { report, address, contractName } = data;
  const lines = [
    "Sentinel Security Report",
    "========================",
    `Address: ${address}`,
    contractName ? `Contract: ${contractName}` : null,
    `Overall Risk Score: ${report.overallRiskScore}/10`,
    `Summary: ${report.summary}`,
    "",
    report.issues.length === 0
      ? "No issues found."
      : `Issues (${report.issues.length}):`,
  ].filter((line): line is string => line !== null);

  report.issues.forEach((issue, index) => {
    lines.push("");
    lines.push(`${index + 1}. [${issue.severity}] ${issue.title}`);
    lines.push(`   ${issue.plainEnglishExplanation}`);
    lines.push(`   Technical: ${issue.technicalDetail}`);
    if (issue.historicalMatch) {
      lines.push(
        `   Resembles: ${issue.historicalMatch} — ${issue.historicalMatchSummary ?? ""}`
      );
    }
  });

  lines.push("");
  lines.push(
    "Generated by Sentinel · AI analysis is not a substitute for a professional audit."
  );
  return lines.join("\n");
}

export default function Home() {
  const [address, setAddress] = useState("");
  const [loading, setLoading] = useState(false);
  const [cooldown, setCooldown] = useState(false);
  const [loadingMsgIndex, setLoadingMsgIndex] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<ScanSuccess | null>(null);
  const [expanded, setExpanded] = useState<Record<number, boolean>>({});
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!loading) {
      setLoadingMsgIndex(0);
      return;
    }
    const id = window.setInterval(() => {
      setLoadingMsgIndex((prev) => (prev + 1) % LOADING_MESSAGES.length);
    }, 2000);
    return () => window.clearInterval(id);
  }, [loading]);

  async function runScan(targetAddress: string) {
    const trimmed = targetAddress.trim();
    if (!trimmed || loading || cooldown) return;

    setLoading(true);
    setCooldown(true);
    setError(null);
    setResult(null);
    setExpanded({});
    setCopied(false);

    window.setTimeout(() => setCooldown(false), 3000);

    try {
      const res = await fetch("/api/scan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ address: trimmed }),
      });

      const data = (await res.json()) as ScanSuccess & { error?: string };

      if (!res.ok || data.error) {
        setError(data.error || "Scan failed. Please try again.");
        return;
      }

      setResult(data);
      window.setTimeout(() => {
        document.getElementById("report")?.scrollIntoView({ behavior: "smooth" });
      }, 80);
    } catch {
      setError("Network error. Check your connection and try again.");
    } finally {
      setLoading(false);
    }
  }

  function handleSubmit(event: FormEvent) {
    event.preventDefault();
    void runScan(address);
  }

  async function handleCopy() {
    if (!result) return;
    try {
      await navigator.clipboard.writeText(formatReportAsText(result));
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      setError("Could not copy to clipboard.");
    }
  }

  const scanDisabled = loading || cooldown || !address.trim();
  const scoreTone = result ? riskTone(result.report.overallRiskScore) : null;

  return (
    <div id="top" className="bg-atmosphere relative min-h-screen text-white">
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute -left-24 top-24 h-72 w-72 rounded-full bg-fuchsia-500/20 blur-[100px]" />
        <div className="absolute right-0 top-10 h-[28rem] w-[28rem] rounded-full bg-violet-600/25 blur-[120px]" />
        <div className="absolute bottom-20 left-1/3 h-64 w-64 rounded-full bg-cyan-400/10 blur-[90px]" />
      </div>

      <aside className="pointer-events-none fixed left-4 top-1/2 z-40 hidden -translate-y-1/2 flex-col gap-4 text-[10px] uppercase tracking-[0.35em] text-white/35 lg:flex">
        <span className="rotate-180 [writing-mode:vertical-rl]">Security</span>
        <span className="h-10 w-px self-center bg-white/20" />
        <span className="rotate-180 [writing-mode:vertical-rl]">Ethereum</span>
      </aside>

      <div className="relative mx-auto w-full max-w-6xl px-4 pb-16 pt-5 sm:px-6 lg:px-8">
        <header className="animate-fade-up sticky top-4 z-50 mx-auto max-w-5xl">
          <nav className="glass flex items-center justify-between gap-3 rounded-full px-3 py-2.5 sm:px-5">
            <a
              href="#top"
              className="display-font flex items-center gap-2 pl-1 text-sm font-bold tracking-wide"
            >
              <span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-gradient-to-br from-fuchsia-400 via-violet-500 to-cyan-400 text-xs text-black">
                S
              </span>
              <span className="hidden sm:inline">SENTINEL</span>
            </a>

            <div className="hidden items-center gap-6 md:flex">
              {NAV_LINKS.map((link) => (
                <a
                  key={link.href}
                  href={link.href}
                  className="text-[11px] font-medium uppercase tracking-[0.22em] text-white/65 transition hover:text-white"
                >
                  {link.label}
                </a>
              ))}
            </div>

            <a
              href="#scan"
              className="btn-primary rounded-full px-4 py-2 text-xs font-semibold uppercase tracking-wide transition sm:px-5 sm:text-[13px]"
            >
              Start Scan
            </a>
          </nav>
        </header>

        <section className="relative mt-10 grid min-h-[78vh] items-center gap-8 lg:mt-6 lg:grid-cols-[1.05fr_0.95fr]">
          <div
            className="animate-fade-up relative z-10 space-y-7"
            style={{ animationDelay: "80ms" }}
          >
            <p className="text-[11px] uppercase tracking-[0.35em] text-violet-200/70">
              AI Smart Contract Security
            </p>
            <h1 className="display-font text-5xl font-extrabold leading-[0.95] tracking-tight sm:text-6xl lg:text-7xl">
              WE ARE
              <br />
              <span className="bg-gradient-to-r from-fuchsia-300 via-violet-200 to-cyan-300 bg-clip-text text-transparent">
                SENTINEL
              </span>
            </h1>
            <p className="max-w-md text-sm leading-relaxed text-violet-100/70 sm:text-base">
              Premium on-chain defense for modern teams. Paste a verified
              Ethereum contract and get a clear, investor-ready risk brief in
              seconds — powered by Google Gemini.
            </p>

            <div className="flex flex-wrap items-center gap-3">
              <a
                href="#scan"
                className="btn-primary inline-flex items-center gap-2 rounded-full py-2 pl-6 pr-2 text-sm font-semibold transition"
              >
                <span>Scan Contract</span>
                <span className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-black/25 text-white">
                  →
                </span>
              </a>
              <a
                href="#about"
                className="glass inline-flex items-center gap-2 rounded-full px-5 py-3 text-sm text-white/80 transition hover:bg-white/10"
              >
                <span className="inline-flex h-6 w-6 items-center justify-center rounded-full bg-violet-400/30 text-[10px]">
                  ▶
                </span>
                How it works
              </a>
            </div>

            <p className="text-xs text-white/40">
              Scans are not stored — your data stays private
            </p>
          </div>

          <div
            className="animate-fade-up relative flex min-h-[360px] items-center justify-center lg:min-h-[520px]"
            style={{ animationDelay: "160ms" }}
          >
            <div className="hero-watermark absolute inset-x-0 top-1/2 -translate-y-1/2 text-center text-[18vw] font-extrabold leading-none sm:text-[9rem] lg:text-[11rem]">
              SENTINEL
            </div>
            <div className="animate-float relative z-10 w-[88%] max-w-md drop-shadow-[0_30px_80px_rgba(168,85,247,0.45)]">
              <Image
                src="/sentinel-hero-form.png"
                alt="Iridescent abstract Sentinel form"
                width={800}
                height={800}
                priority
                className="h-auto w-full select-none"
              />
            </div>

            <div className="absolute bottom-2 right-2 hidden h-24 w-24 items-center justify-center sm:flex lg:bottom-8 lg:right-0">
              <svg
                viewBox="0 0 100 100"
                className="scroll-ring absolute inset-0 h-full w-full"
              >
                <defs>
                  <path
                    id="circlePath"
                    d="M 50, 50 m -36, 0 a 36,36 0 1,1 72,0 a 36,36 0 1,1 -72,0"
                  />
                </defs>
                <text className="fill-white/50 text-[9px] uppercase tracking-[0.28em]">
                  <textPath href="#circlePath">
                    Scroll to explore · Sentinel ·{" "}
                  </textPath>
                </text>
              </svg>
              <span className="text-lg text-white/70">↓</span>
            </div>
          </div>
        </section>

        <section id="scan" className="relative z-10 mt-6 scroll-mt-28 sm:mt-10">
          <div className="glass-strong animate-fade-up rounded-[2rem] p-5 sm:p-8">
            <div className="mb-6 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
              <div>
                <p className="text-[11px] uppercase tracking-[0.3em] text-violet-200/60">
                  Live Scanner
                </p>
                <h2 className="display-font mt-2 text-2xl font-bold sm:text-3xl">
                  Paste an address. Get clarity.
                </h2>
              </div>
              <p className="max-w-sm text-sm text-white/45">
                Works with verified Ethereum mainnet contracts via Etherscan.
              </p>
            </div>

            <form onSubmit={handleSubmit} className="space-y-4">
              <label htmlFor="address" className="sr-only">
                Ethereum contract address
              </label>
              <div className="flex flex-col gap-3 sm:flex-row">
                <input
                  id="address"
                  type="text"
                  value={address}
                  onChange={(e) => setAddress(e.target.value)}
                  placeholder="Paste an Ethereum contract address (0x...)"
                  spellCheck={false}
                  className="input-glow w-full rounded-full border border-white/15 bg-black/35 px-5 py-4 text-sm text-white outline-none transition placeholder:text-white/35 sm:text-base"
                />
                <button
                  type="submit"
                  disabled={scanDisabled}
                  className="btn-primary shrink-0 rounded-full px-8 py-4 text-sm font-semibold transition sm:min-w-[160px]"
                >
                  {loading
                    ? "Scanning..."
                    : cooldown
                      ? "Please wait..."
                      : "Scan"}
                </button>
              </div>
            </form>

            <div className="mt-5 flex flex-wrap gap-2">
              {EXAMPLE_CONTRACTS.map((example) => (
                <button
                  key={example.address}
                  type="button"
                  onClick={() => setAddress(example.address)}
                  className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs text-white/70 transition hover:border-fuchsia-300/40 hover:bg-white/10 hover:text-white sm:text-sm"
                >
                  {example.label}
                </button>
              ))}
            </div>

            {loading && (
              <div className="mt-6 flex items-center gap-3 rounded-2xl border border-white/10 bg-black/25 px-4 py-4 text-violet-100/80">
                <div className="spinner" aria-hidden />
                <p className="text-sm sm:text-base">
                  {LOADING_MESSAGES[loadingMsgIndex]}
                </p>
              </div>
            )}

            {error && !loading && (
              <div className="mt-6 rounded-2xl border border-rose-400/30 bg-rose-500/10 px-4 py-4 sm:px-5">
                <p className="text-sm text-rose-100 sm:text-base">{error}</p>
                <button
                  type="button"
                  onClick={() => void runScan(address)}
                  disabled={!address.trim() || cooldown}
                  className="mt-3 text-sm font-medium text-rose-50 underline underline-offset-2 hover:text-white disabled:opacity-50"
                >
                  Retry scan
                </button>
              </div>
            )}
          </div>
        </section>

        <section
          id="about"
          className="relative mt-16 grid scroll-mt-28 gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"
        >
          <div className="relative hidden min-h-[280px] lg:block">
            <div className="hero-watermark absolute -left-6 top-8 text-[7rem] font-extrabold leading-none">
              ABOUT
            </div>
            <div className="absolute bottom-0 left-0 w-[70%] opacity-80">
              <Image
                src="/sentinel-hero-form.png"
                alt=""
                width={500}
                height={500}
                className="h-auto w-full scale-x-[-1] rotate-180 opacity-70"
              />
            </div>
          </div>

          <div className="space-y-5">
            <p className="text-[11px] uppercase tracking-[0.35em] text-violet-200/60">
              Who we are
            </p>
            <h2 className="display-font text-3xl font-bold leading-tight sm:text-4xl">
              Security intelligence with a cinematic edge.
            </h2>
            <p className="max-w-xl text-sm leading-relaxed text-white/55 sm:text-base">
              Sentinel fetches verified Solidity from Etherscan, then asks Gemini
              to hunt for reentrancy, access-control flaws, dangerous external
              calls, and other high-impact risks — translating findings into
              plain English with optional historical exploit parallels.
            </p>
            <div className="grid gap-3 sm:grid-cols-3">
              {[
                ["01", "Fetch", "Verified source via Etherscan V2"],
                ["02", "Analyze", "Gemini Flash security audit"],
                ["03", "Report", "Risk score + plain-English issues"],
              ].map(([n, title, copy]) => (
                <div key={n} className="glass rounded-2xl p-4">
                  <p className="text-[11px] text-fuchsia-300/80">{n}</p>
                  <p className="mt-1 font-semibold">{title}</p>
                  <p className="mt-1 text-xs text-white/45">{copy}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {result && !loading && scoreTone && (
          <section id="report" className="mt-14 scroll-mt-28 space-y-5">
            <div className="glass-strong animate-fade-up rounded-[2rem] p-5 sm:p-8">
              <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-center">
                <div
                  className={`inline-flex items-center gap-4 rounded-3xl border px-5 py-4 ${scoreTone.chip}`}
                >
                  <span className="display-font text-5xl font-extrabold tabular-nums sm:text-6xl">
                    {result.report.overallRiskScore}
                  </span>
                  <div>
                    <p className="text-sm font-semibold">/ 10</p>
                    <p className="text-xs opacity-80">{scoreTone.label}</p>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={() => void handleCopy()}
                  className="glass rounded-full px-5 py-3 text-sm text-white/85 transition hover:bg-white/10"
                >
                  {copied ? "Copied!" : "Copy Report"}
                </button>
              </div>

              <p className="mt-6 text-lg leading-relaxed text-violet-50 sm:text-xl">
                {result.report.summary}
              </p>

              {result.contractName && (
                <p className="mt-3 text-xs text-white/40">
                  Contract: {result.contractName}
                  {result.truncated ? " · Source truncated for analysis" : ""}
                </p>
              )}
            </div>

            {result.report.issues.length === 0 ? (
              <div className="animate-fade-up rounded-[1.75rem] border border-emerald-400/25 bg-emerald-500/10 px-5 py-6">
                <p className="text-lg font-semibold text-emerald-300">
                  No issues found in this scan
                </p>
                <p className="mt-2 text-sm leading-relaxed text-emerald-50/80">
                  Looking good from an automated pass — but AI analysis isn&apos;t
                  a substitute for a professional security audit before you put
                  real funds at risk.
                </p>
              </div>
            ) : (
              <ul className="space-y-3">
                {result.report.issues.map((issue, index) => {
                  const open = !!expanded[index];
                  return (
                    <li
                      key={`${issue.title}-${index}`}
                      className="glass animate-fade-up rounded-[1.5rem] p-4 sm:p-5"
                      style={{ animationDelay: `${index * 60}ms` }}
                    >
                      <div className="flex flex-wrap items-center gap-2">
                        <span
                          className={`rounded-full border px-2.5 py-0.5 text-xs font-semibold ${severityTone(issue.severity)}`}
                        >
                          {issue.severity}
                        </span>
                        <h3 className="text-base font-semibold text-white sm:text-lg">
                          {issue.title}
                        </h3>
                      </div>

                      <p className="mt-3 text-sm leading-relaxed text-white/65 sm:text-base">
                        {issue.plainEnglishExplanation}
                      </p>

                      <button
                        type="button"
                        onClick={() =>
                          setExpanded((prev) => ({
                            ...prev,
                            [index]: !prev[index],
                          }))
                        }
                        className="mt-3 text-sm text-fuchsia-300 underline-offset-2 hover:underline"
                      >
                        {open ? "Hide Technical Details" : "Technical Details"}
                      </button>

                      {open && (
                        <p className="mt-3 rounded-2xl border border-white/10 bg-black/30 px-3 py-3 font-mono text-sm leading-relaxed text-white/50">
                          {issue.technicalDetail}
                        </p>
                      )}

                      {issue.historicalMatch && (
                        <div className="mt-3 rounded-2xl border border-amber-400/30 bg-amber-400/10 px-3 py-3 text-sm text-amber-50">
                          ⚠️ Resembles: {issue.historicalMatch}
                          {issue.historicalMatchSummary
                            ? ` — ${issue.historicalMatchSummary}`
                            : ""}
                        </div>
                      )}
                    </li>
                  );
                })}
              </ul>
            )}
          </section>
        )}

        <footer className="mt-16 border-t border-white/10 pt-8 text-center text-xs text-white/35 sm:text-sm">
          Powered by Google Gemini · Built for ETHGlobal
        </footer>
      </div>
    </div>
  );
}
