"use client";

import { FormEvent, useEffect, useState } from "react";

type Severity = "Critical" | "High" | "Medium" | "Low" | "Info";

type Issue = {
  title: string;
  severity: Severity | string;
  plainEnglishExplanation: string;
  technicalDetail: string;
  historicalMatch: string | null;
  historicalMatchSummary: string | null;
};

type Report = {
  overallRiskScore: number;
  summary: string;
  issues: Issue[];
};

type ScanSuccess = {
  address: string;
  contractName: string | null;
  truncated: boolean;
  report: Report;
};

const EXAMPLE_CONTRACTS = [
  {
    label: "Try USDC",
    address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
  },
  {
    label: "Try Uniswap Router",
    address: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D",
  },
  {
    label: "Try WETH",
    address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
  },
] as const;

const LOADING_MESSAGES = [
  "Fetching contract source...",
  "Analyzing with AI...",
] as const;

function riskTone(score: number): { badge: string; label: string } {
  if (score <= 3) {
    return {
      badge: "bg-emerald-500/15 text-emerald-400 border-emerald-500/40",
      label: "Low risk",
    };
  }
  if (score <= 6) {
    return {
      badge: "bg-amber-500/15 text-amber-300 border-amber-500/40",
      label: "Moderate risk",
    };
  }
  return {
    badge: "bg-red-500/15 text-red-400 border-red-500/40",
    label: "High risk",
  };
}

function severityTone(severity: string): string {
  switch (severity) {
    case "Critical":
      return "bg-red-500/20 text-red-300 border-red-500/40";
    case "High":
      return "bg-orange-500/20 text-orange-300 border-orange-500/40";
    case "Medium":
      return "bg-yellow-500/20 text-yellow-200 border-yellow-500/40";
    case "Low":
      return "bg-sky-500/20 text-sky-300 border-sky-500/40";
    default:
      return "bg-slate-500/20 text-slate-300 border-slate-500/40";
  }
}

function formatReportAsText(data: ScanSuccess): string {
  const { report, address, contractName } = data;
  const lines = [
    "Sentinel Security Report",
    "========================",
    `Address: ${address}`,
    contractName ? `Contract: ${contractName}` : null,
    `Overall Risk Score: ${report.overallRiskScore}/10`,
    `Summary: ${report.summary}`,
    "",
    report.issues.length === 0
      ? "No issues found."
      : `Issues (${report.issues.length}):`,
  ].filter((line): line is string => line !== null);

  report.issues.forEach((issue, index) => {
    lines.push("");
    lines.push(`${index + 1}. [${issue.severity}] ${issue.title}`);
    lines.push(`   ${issue.plainEnglishExplanation}`);
    lines.push(`   Technical: ${issue.technicalDetail}`);
    if (issue.historicalMatch) {
      lines.push(
        `   Resembles: ${issue.historicalMatch} — ${issue.historicalMatchSummary ?? ""}`
      );
    }
  });

  lines.push("");
  lines.push(
    "Generated by Sentinel · AI analysis is not a substitute for a professional audit."
  );
  return lines.join("\n");
}

export default function Home() {
  const [address, setAddress] = useState("");
  const [loading, setLoading] = useState(false);
  const [cooldown, setCooldown] = useState(false);
  const [loadingMsgIndex, setLoadingMsgIndex] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<ScanSuccess | null>(null);
  const [expanded, setExpanded] = useState<Record<number, boolean>>({});
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    if (!loading) {
      setLoadingMsgIndex(0);
      return;
    }
    const id = window.setInterval(() => {
      setLoadingMsgIndex((prev) => (prev + 1) % LOADING_MESSAGES.length);
    }, 2000);
    return () => window.clearInterval(id);
  }, [loading]);

  async function runScan(targetAddress: string) {
    const trimmed = targetAddress.trim();
    if (!trimmed || loading || cooldown) return;

    setLoading(true);
    setCooldown(true);
    setError(null);
    setResult(null);
    setExpanded({});
    setCopied(false);

    window.setTimeout(() => setCooldown(false), 3000);

    try {
      const res = await fetch("/api/scan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ address: trimmed }),
      });

      const data = (await res.json()) as ScanSuccess & { error?: string };

      if (!res.ok || data.error) {
        setError(data.error || "Scan failed. Please try again.");
        return;
      }

      setResult(data);
    } catch {
      setError("Network error. Check your connection and try again.");
    } finally {
      setLoading(false);
    }
  }

  function handleSubmit(event: FormEvent) {
    event.preventDefault();
    void runScan(address);
  }

  async function handleCopy() {
    if (!result) return;
    try {
      await navigator.clipboard.writeText(formatReportAsText(result));
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      setError("Could not copy to clipboard.");
    }
  }

  const scanDisabled = loading || cooldown || !address.trim();
  const scoreTone = result ? riskTone(result.report.overallRiskScore) : null;

  return (
    <main className="min-h-screen bg-[#050a14] px-4 py-10 text-white sm:px-6 sm:py-14">
      <div className="mx-auto flex w-full max-w-[800px] flex-col gap-8">
        <header className="space-y-3 text-center">
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">
            🛡️ Sentinel
          </h1>
          <p className="text-base text-slate-300 sm:text-lg">
            AI-Powered Smart Contract Security Scanner
          </p>
          <p className="text-xs text-slate-500 sm:text-sm">
            Scans are not stored — your data stays private
          </p>
        </header>

        <section className="rounded-2xl border border-slate-800 bg-[#0b1220] p-5 sm:p-6">
          <form onSubmit={handleSubmit} className="space-y-4">
            <label htmlFor="address" className="sr-only">
              Ethereum contract address
            </label>
            <input
              id="address"
              type="text"
              value={address}
              onChange={(e) => setAddress(e.target.value)}
              placeholder="Paste an Ethereum contract address (0x...)"
              spellCheck={false}
              className="w-full rounded-xl border border-slate-700 bg-[#050a14] px-4 py-3.5 text-sm text-white outline-none transition placeholder:text-slate-500 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/30 sm:text-base"
            />
            <button
              type="submit"
              disabled={scanDisabled}
              className="w-full rounded-xl bg-blue-500 px-4 py-3.5 text-sm font-semibold text-white transition hover:bg-blue-400 disabled:cursor-not-allowed disabled:opacity-50 sm:text-base"
            >
              {loading
                ? "Scanning..."
                : cooldown
                  ? "Please wait..."
                  : "Scan Contract"}
            </button>
          </form>

          <div className="mt-4 flex flex-wrap gap-2">
            {EXAMPLE_CONTRACTS.map((example) => (
              <button
                key={example.address}
                type="button"
                onClick={() => setAddress(example.address)}
                className="rounded-lg border border-slate-700 bg-[#050a14] px-3 py-1.5 text-xs text-slate-300 transition hover:border-blue-500 hover:text-white sm:text-sm"
              >
                {example.label}
              </button>
            ))}
          </div>
        </section>

        {loading && (
          <div className="animate-fade-in flex items-center justify-center gap-3 rounded-xl border border-slate-800 bg-[#0b1220] px-4 py-6 text-slate-300">
            <div className="spinner" aria-hidden />
            <p className="text-sm sm:text-base">
              {LOADING_MESSAGES[loadingMsgIndex]}
            </p>
          </div>
        )}

        {error && !loading && (
          <div className="animate-fade-in rounded-xl border border-red-500/40 bg-red-500/10 px-4 py-4 sm:px-5">
            <p className="text-sm text-red-200 sm:text-base">{error}</p>
            <button
              type="button"
              onClick={() => void runScan(address)}
              disabled={!address.trim() || cooldown}
              className="mt-3 text-sm font-medium text-red-100 underline underline-offset-2 hover:text-white disabled:opacity-50"
            >
              Retry scan
            </button>
          </div>
        )}

        {result && !loading && scoreTone && (
          <section className="animate-fade-in space-y-5">
            <div className="space-y-5 rounded-2xl border border-slate-800 bg-[#0b1220] p-5 sm:p-6">
              <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center">
                <div
                  className={`inline-flex items-center gap-3 rounded-2xl border px-4 py-3 ${scoreTone.badge}`}
                >
                  <span className="text-4xl font-bold tabular-nums sm:text-5xl">
                    {result.report.overallRiskScore}
                  </span>
                  <div className="text-left">
                    <p className="text-sm font-semibold">/ 10</p>
                    <p className="text-xs opacity-80">{scoreTone.label}</p>
                  </div>
                </div>

                <button
                  type="button"
                  onClick={() => void handleCopy()}
                  className="rounded-xl border border-slate-700 bg-[#050a14] px-4 py-2.5 text-sm text-slate-200 transition hover:border-blue-500 hover:text-white"
                >
                  {copied ? "Copied!" : "Copy Report"}
                </button>
              </div>

              <p className="text-lg leading-relaxed text-slate-100 sm:text-xl">
                {result.report.summary}
              </p>

              {result.contractName && (
                <p className="text-xs text-slate-500">
                  Contract: {result.contractName}
                  {result.truncated ? " · Source truncated for analysis" : ""}
                </p>
              )}
            </div>

            {result.report.issues.length === 0 ? (
              <div className="space-y-2 rounded-2xl border border-emerald-500/30 bg-emerald-500/10 px-5 py-6">
                <p className="text-lg font-semibold text-emerald-300">
                  No issues found in this scan
                </p>
                <p className="text-sm leading-relaxed text-emerald-100/80">
                  Looking good from an automated pass — but AI analysis isn&apos;t
                  a substitute for a professional security audit before you put
                  real funds at risk.
                </p>
              </div>
            ) : (
              <ul className="space-y-3">
                {result.report.issues.map((issue, index) => {
                  const open = !!expanded[index];
                  return (
                    <li
                      key={`${issue.title}-${index}`}
                      className="space-y-3 rounded-2xl border border-slate-800 bg-[#0b1220] p-4 sm:p-5"
                    >
                      <div className="flex flex-wrap items-center gap-2">
                        <span
                          className={`rounded-md border px-2 py-0.5 text-xs font-semibold ${severityTone(issue.severity)}`}
                        >
                          {issue.severity}
                        </span>
                        <h3 className="text-base font-semibold text-white sm:text-lg">
                          {issue.title}
                        </h3>
                      </div>

                      <p className="text-sm leading-relaxed text-slate-300 sm:text-base">
                        {issue.plainEnglishExplanation}
                      </p>

                      <button
                        type="button"
                        onClick={() =>
                          setExpanded((prev) => ({
                            ...prev,
                            [index]: !prev[index],
                          }))
                        }
                        className="text-sm text-blue-400 underline-offset-2 hover:underline"
                      >
                        {open ? "Hide Technical Details" : "Technical Details"}
                      </button>

                      {open && (
                        <p className="rounded-xl border border-slate-700 bg-[#050a14] px-3 py-3 font-mono text-sm leading-relaxed text-slate-400">
                          {issue.technicalDetail}
                        </p>
                      )}

                      {issue.historicalMatch && (
                        <div className="rounded-xl border border-amber-500/30 bg-amber-500/10 px-3 py-3 text-sm text-amber-100">
                          ⚠️ Resembles: {issue.historicalMatch}
                          {issue.historicalMatchSummary
                            ? ` — ${issue.historicalMatchSummary}`
                            : ""}
                        </div>
                      )}
                    </li>
                  );
                })}
              </ul>
            )}
          </section>
        )}

        <footer className="pb-2 pt-4 text-center text-xs text-slate-500 sm:text-sm">
          Powered by Google Gemini · Built for ETHGlobal
        </footer>
      </div>
    </main>
  );
}
